project:
  type: website
  output-dir: docs

website:
  title: "Malariasimulation Workshop"
  navbar:
    logo: "presentations/images/malariasimulation_logo.png"
    left:
      - text: "Home"
        file: index.qmd
      - text: "Workshop materials"
        file: materials.qmd
  page-footer:
    left: "This workshop was created with ❤️, [Learnr](https://rstudio.github.io/learnr/) and [Quarto](https://quarto.org/) by Lydia Haile, Richard Sheppard, Tom Brewer & Pete Winskill."

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

